/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_klatencor_klara_future_support_JniDataOperations */

#ifndef _Included_com_klatencor_klara_future_support_JniDataOperations
#define _Included_com_klatencor_klara_future_support_JniDataOperations
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_klatencor_klara_future_support_JniDataOperations
 * Method:    loadRecipe
 * Signature: (Ljava/lang/String;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_klatencor_klara_future_support_JniDataOperations_loadRecipe
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_klatencor_klara_future_support_JniDataOperations
 * Method:    writeRecipe
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_klatencor_klara_future_support_JniDataOperations_writeRecipe
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_klatencor_klara_future_support_JniDataOperations
 * Method:    closeRecipe
 * Signature: (Ljava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_klatencor_klara_future_support_JniDataOperations_closeRecipe
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_klatencor_klara_future_support_JniDataOperations
 * Method:    updateRecipe
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_klatencor_klara_future_support_JniDataOperations_updateRecipe
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_klatencor_klara_future_support_JniDataOperations
 * Method:    queryRecipe
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_klatencor_klara_future_support_JniDataOperations_queryRecipe
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_klatencor_klara_future_support_JniDataOperations
 * Method:    jniUpdateSetName
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_klatencor_klara_future_support_JniDataOperations_jniUpdateSetName
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_klatencor_klara_future_support_JniDataOperations
 * Method:    jniGetPlateAlignmentImages
 * Signature: (Ljava/nio/ByteBuffer;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_klatencor_klara_future_support_JniDataOperations_jniGetPlateAlignmentImages
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_klatencor_klara_future_support_JniDataOperations
 * Method:    jniUpdateSenseSlider
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_klatencor_klara_future_support_JniDataOperations_jniUpdateSenseSlider
  (JNIEnv *, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
