/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.smartframework.jobhub.protocol;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum JobState implements org.apache.thrift.TEnum {
  PREPARE(1),
  SUBMITTED(2),
  RUNNING(3),
  RESCHEDULE(4),
  DONE(5);

  private final int value;

  private JobState(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static JobState findByValue(int value) { 
    switch (value) {
      case 1:
        return PREPARE;
      case 2:
        return SUBMITTED;
      case 3:
        return RUNNING;
      case 4:
        return RESCHEDULE;
      case 5:
        return DONE;
      default:
        return null;
    }
  }
}
